//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaAlmacenes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoEtiqueta
    {
        public int idProducto { get; set; }
        public int idEtiqueta { get; set; }
    
        public virtual Etiqueta Etiqueta { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
